name: DreamsPlugin
main: com.Tiger.dreamings.DreamsPlugin
version: ${project.version}
api-version: 1.20
author: __Tiger
description: A simple plugin that adds dream and nightmare mechanics to Minecraft.

commands:
  dreams:
    description: Comando principal do DreamsPlugin (setdream / setnightmare / reload).
    usage: /dreams <setdream|setnightmare|reload>
    aliases: [setdream, setnightmare]
    permission: dreams.admin

permissions:
  dreams.admin:
    description: Permite usar comandos administrativos e recarregar.
    default: op
  dreams.set:
    description: Permite definir os locais de sonho e pesadelo.
    default: op