name: DreamsPlugin
main: com.Tiger.dreamings.DreamsPlugin
version: 1.0
api-version: 1.20
author: __Tiger
description: A simple plugin that adds dream and nightmare mechanics to Minecraft.

commands:
  setdream:
    description: Define a posição atual como local do sonho
    permission: dreams.set
    usage: /setdream
  setnightmare:
    description: Define a posição atual como local do pesadelo
    permission: dreams.set
    usage: /setnightmare
  dreams:
    description: Comando administrativo do DreamsPlugin.
    usage: /<command> reload
    permission: dreams.admin

permissions:
  dreams.admin:
    description: Permite usar comandos administrativos
    default: op
  dreams.set:
    description: Permite definir os locais de sonho e pesadelo.
    default: op